# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: LiteLLM
version: "1.0.23"
slug: litellm
description: >-
  AI gateway for Claude Code and Claude Desktop using OpenRouter.
url: https://github.com/nishantapatil3/hassio-apps/tree/main/litellm
arch:
  - aarch64
  - amd64
init: false
backup: cold
ports:
  4000/tcp: 4000
ports_description:
  4000/tcp: LiteLLM API and admin UI
webui: http://[HOST]:[PORT:4000]/ui
map:
  - type: addon_config
    read_only: false
options:
  master_key: "sk-1234"
  database_host: "db21ed7f-postgres"
  server_root_path: ""
schema:
  master_key: str
  database_host: str
  server_root_path: str
image: ghcr.io/nishantapatil3/hassio-apps-litellm
